package db;
// Generated Sep 2, 2012 12:30:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String author;
     private String genre;
     private int edition;
     private int year;
     private String publisher;
     private String isbn;
     private String description;
     private String picture;
     private Boolean takeAway;
     private Boolean paperVersion;
     private String pdf;
     private int numOfCopies;
     private Set<Taken> takens = new HashSet<Taken>(0);
     private Set<Reservation> reservations = new HashSet<Reservation>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);

    public Book() {
    }

	
    public Book(String title, String author, String genre, int edition, int year, String publisher, String isbn, String description, int numOfCopies) {
        this.title = title;
        this.author = author;
        this.genre = genre;
        this.edition = edition;
        this.year = year;
        this.publisher = publisher;
        this.isbn = isbn;
        this.description = description;
        this.numOfCopies = numOfCopies;
    }
    public Book(String title, String author, String genre, int edition, int year, String publisher, String isbn, String description, String picture, Boolean takeAway, Boolean paperVersion, String pdf, int numOfCopies, Set<Taken> takens, Set<Reservation> reservations, Set<Comment> comments) {
       this.title = title;
       this.author = author;
       this.genre = genre;
       this.edition = edition;
       this.year = year;
       this.publisher = publisher;
       this.isbn = isbn;
       this.description = description;
       this.picture = picture;
       this.takeAway = takeAway;
       this.paperVersion = paperVersion;
       this.pdf = pdf;
       this.numOfCopies = numOfCopies;
       this.takens = takens;
       this.reservations = reservations;
       this.comments = comments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public int getEdition() {
        return this.edition;
    }
    
    public void setEdition(int edition) {
        this.edition = edition;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public Boolean getTakeAway() {
        return this.takeAway;
    }
    
    public void setTakeAway(Boolean takeAway) {
        this.takeAway = takeAway;
    }
    public Boolean getPaperVersion() {
        return this.paperVersion;
    }
    
    public void setPaperVersion(Boolean paperVersion) {
        this.paperVersion = paperVersion;
    }
    public String getPdf() {
        return this.pdf;
    }
    
    public void setPdf(String pdf) {
        this.pdf = pdf;
    }
    public int getNumOfCopies() {
        return this.numOfCopies;
    }
    
    public void setNumOfCopies(int numOfCopies) {
        this.numOfCopies = numOfCopies;
    }
    public Set<Taken> getTakens() {
        return this.takens;
    }
    
    public void setTakens(Set<Taken> takens) {
        this.takens = takens;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }




}


