package db;
// Generated Sep 2, 2012 12:30:19 PM by Hibernate Tools 3.2.1.GA



/**
 * Const generated by hbm2java
 */
public class Const  implements java.io.Serializable {


     private Integer id;
     private int m;
     private int n;
     private int s;
     private int p;

    public Const() {
    }

    public Const(int m, int n, int s, int p) {
       this.m = m;
       this.n = n;
       this.s = s;
       this.p = p;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getM() {
        return this.m;
    }
    
    public void setM(int m) {
        this.m = m;
    }
    public int getN() {
        return this.n;
    }
    
    public void setN(int n) {
        this.n = n;
    }
    public int getS() {
        return this.s;
    }
    
    public void setS(int s) {
        this.s = s;
    }
    public int getP() {
        return this.p;
    }
    
    public void setP(int p) {
        this.p = p;
    }




}


