package db;
// Generated Sep 2, 2012 12:30:19 PM by Hibernate Tools 3.2.1.GA



/**
 * MonthlyAward generated by hbm2java
 */
public class MonthlyAward  implements java.io.Serializable {


     private Integer id;
     private User user;
     private int year;
     private int month;

    public MonthlyAward() {
    }

    public MonthlyAward(User user, int year, int month) {
       this.user = user;
       this.year = year;
       this.month = month;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public int getMonth() {
        return this.month;
    }
    
    public void setMonth(int month) {
        this.month = month;
    }




}


