package db;
// Generated Aug 24, 2012 3:12:26 AM by Hibernate Tools 3.2.1.GA



/**
 * ReservationId generated by hbm2java
 */
public class ReservationId  implements java.io.Serializable {


     private int userId;
     private int bookId;

    public ReservationId() {
    }

    public ReservationId(int userId, int bookId) {
       this.userId = userId;
       this.bookId = bookId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getBookId() {
        return this.bookId;
    }
    
    public void setBookId(int bookId) {
        this.bookId = bookId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservationId) ) return false;
		 ReservationId castOther = ( ReservationId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getBookId()==castOther.getBookId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getBookId();
         return result;
   }   


}


