package db;
// Generated Sep 2, 2012 12:30:19 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private User user;
     private Book book;

    public Reservation() {
    }

    public Reservation(User user, Book book) {
       this.user = user;
       this.book = book;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }




}


