package db;
// Generated Sep 2, 2012 12:30:19 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Taken generated by hbm2java
 */
public class Taken  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private User user;
     private Book book;
     private Boolean back;
     private Boolean hadPenalty;

    public Taken() {
    }

	
    public Taken(User user, Book book) {
        this.user = user;
        this.book = book;
    }
    public Taken(User user, Book book, Boolean back, Boolean hadPenalty) {
       this.user = user;
       this.book = book;
       this.back = back;
       this.hadPenalty = hadPenalty;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Boolean getBack() {
        return this.back;
    }
    
    public void setBack(Boolean back) {
        this.back = back;
    }
    public Boolean getHadPenalty() {
        return this.hadPenalty;
    }
    
    public void setHadPenalty(Boolean hadPenalty) {
        this.hadPenalty = hadPenalty;
    }




}


