package db;
// Generated Sep 2, 2012 12:30:19 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private String name;
     private String surname;
     private String username;
     private String password;
     private String city;
     private String address;
     private String telephone;
     private String email;
     private String type;
     private Boolean active;
     private Set<Taken> takens = new HashSet<Taken>(0);
     private Set<Reservation> reservations = new HashSet<Reservation>(0);
     private Set<MonthlyAward> monthlyAwards = new HashSet<MonthlyAward>(0);
     private Set<YearlyAward> yearlyAwards = new HashSet<YearlyAward>(0);

    public User() {
    }

	
    public User(String name, String surname, String username, String password, String type) {
        this.name = name;
        this.surname = surname;
        this.username = username;
        this.password = password;
        this.type = type;
    }
    public User(String name, String surname, String username, String password, String city, String address, String telephone, String email, String type, Boolean active, Set<Taken> takens, Set<Reservation> reservations, Set<MonthlyAward> monthlyAwards, Set<YearlyAward> yearlyAwards) {
       this.name = name;
       this.surname = surname;
       this.username = username;
       this.password = password;
       this.city = city;
       this.address = address;
       this.telephone = telephone;
       this.email = email;
       this.type = type;
       this.active = active;
       this.takens = takens;
       this.reservations = reservations;
       this.monthlyAwards = monthlyAwards;
       this.yearlyAwards = yearlyAwards;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set<Taken> getTakens() {
        return this.takens;
    }
    
    public void setTakens(Set<Taken> takens) {
        this.takens = takens;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }
    public Set<MonthlyAward> getMonthlyAwards() {
        return this.monthlyAwards;
    }
    
    public void setMonthlyAwards(Set<MonthlyAward> monthlyAwards) {
        this.monthlyAwards = monthlyAwards;
    }
    public Set<YearlyAward> getYearlyAwards() {
        return this.yearlyAwards;
    }
    
    public void setYearlyAwards(Set<YearlyAward> yearlyAwards) {
        this.yearlyAwards = yearlyAwards;
    }




}


